version: '3.8'
services:

  nestjs-dev-db:
    image: postgres:15
    hostname: nestjs-dev-db-hostname
    environment:
      POSTGRES_USER: nhatcomnhom
      POSTGRES_PASSWORD: nhatcomnhom
      POSTGRES_DB: nhatcomnhom-db
      # POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    # volumes:
    #   - ./dbdata:/var/lib/postgresql/data
    #   # - ./db_postgres:/docker-entrypoint-initdb.d
    # restart: always
    ports:
      - 5432:5432
    networks:
      - nestjs-dev-networks

networks:
  nestjs-dev-networks: