version: '3.8'
services:

  nestjs-dev-db:
    image: postgres:15
    hostname: nestjs-dev-db-hostname
    environment:
      POSTGRES_USER: nhatcomnhom
      POSTGRES_PASSWORD: nhatcomnhom
      POSTGRES_DB: nhatcomnhom-db
    ports:
      - 5432:5432
    networks:
      - nestjs-networks
  
  nestjs-test-db:
    image: postgres:15
    hostname: nestjs-test-db-hostname
    environment:
      POSTGRES_USER: nhatcomnhom
      POSTGRES_PASSWORD: nhatcomnhom
      POSTGRES_DB: nhatcomnhom-db
    ports:
      - 5435:5432
    networks:
      - nestjs-networks

networks:
  nestjs-networks: